const defaultCommands = [
  {
    command: 'dadjoke',
    response: '#dadJoke',
    showInCommands: false,
    isEnabled: true,
    modOnly: false,
    cooldown: 300,
    defaultCommand: true,
  },
  {
    command: '!ping',
    response: '#ping',
    description: 'A fun command that just returns "Pong!" meant to test if the bot is active',
    showInCommands: true,
    isEnabled: true,
    modOnly: false,
    cooldown: 60,
    defaultCommand: true,
  },
  {
    command: '!settitle',
    showInCommands: true,
    description: 'This command sets the title of the stream',
    response: '#setTitle',
    isEnabled: true,
    modOnly: true,
    cooldown: 0,
    defaultCommand: true,
  },
  {   
    command: '!setcategory',
    showInCommands: true,
    description: 'This command sets the category of the stream',
    response: '#setCategory',
    isEnabled: true,
    modOnly: true,
    cooldown: 0,
    defaultCommand: true,
  },
  {
    command: '!addbot',
    showInCommands: true,
    description: 'This command give the link to add the bot to your channel',
    response: 'Want to add BeepBoBoopBot to your own channel? Click this link: https://id.twitch.tv/oauth2/authorize?client_id=y5o7q9tom9z1do6hi4466ttwr6vs8s&redirect_uri=https://beepboboopbot.herokuapp.com/addBot&response_type=code&scope=channel:manage:broadcast',
    modOnly: false,
    isEnabled: true,
    cooldown: 60,
    defaultCommand: true,
  },
  {
    command: '!removebot',
    showInCommands: true,
    description: 'This command give the link to remove the bot from your channel',
    response: 'To remove the bot, the broadcaster must click this link: https://id.twitch.tv/oauth2/authorize?client_id=y5o7q9tom9z1do6hi4466ttwr6vs8s&redirect_uri=https://beepboboopbot.herokuapp.com/removeBot&response_type=code',
    modOnly: true,
    isEnabled: true,
    cooldown: 60,
    defaultCommand: true,
  },
  {
    command: '!level',
    response: '#getLevel',
    showInCommands: true,
    description: 'This command responds to the user with their xp and level',
    modOnly: false,
    isEnabled: true,
    cooldown: 0,
    defaultCommand: true,
  },
  {
    command: '!leaderboard',
    response: '#getProfileURL',
    showInCommands: true,
    description: 'This command give the link to the channel\'s xp leaderboard and commands',
    modOnly: false,
    isEnabled: true,
    cooldown: 60,
    defaultCommand: true,
  },
  {
    command: '!commands',
    response: '#getProfileURL',
    showInCommands: true,
    description: 'This command give the link to the channel\'s xp leaderboard and commands',
    modOnly: false,
    isEnabled: true,
    cooldown: 60,
    defaultCommand: true,
  },
  {
    command: '!togglelevelupnotifications',
    response: '#toggleLevelUpNotifications',
    showInCommands: true,
    description: 'This command toggles the level up notifications that appear in chat',
    modOnly: true,
    isEnabled: true,
    cooldown: 0,
    defaultCommand: true,
  },
  {
    command: '!updateDefaultCommands',
    response: '#updateDefaultCommands',
    description: 'This command adds all default commands that currently don\'t exist for your stream',
    showInCommands: true,
    isEnabled: true,
    modOnly: true,
    cooldown: 0,
    defaultCommand: true,
  },
  {
    command: '!togglecommand',
    response: '#toggleCommand',
    description: 'This command toggles a command to be enabled or disabled. This DOES apply to default commands',
    showInCommands: true,
    isEnabled: true,
    modOnly: false,
    cooldown: 0,
    defaultCommand: true,
  }
]

module.exports = {
  defaultCommands,
}